### ISSUE TITLE
Add 'filter' block to EC2 service data source that are currently missing this

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We should add a `filter` configuration block to those EC2 service (those classified in our documentation as **Provider**, **EC2** or **VPC**) data sources that currently do not have one. This allows the ability to filter on AWS resource attributes that are not mapped to Terraform attributes.

### Affected Data Sources

* [x] [`aws_availability_zone`](https://www.terraform.io/docs/providers/aws/d/availability_zone.html) - https://github.com/terraform-providers/terraform-provider-aws/issues/11136, https://github.com/terraform-providers/terraform-provider-aws/pull/12400
* [x] [`aws_availability_zones`](https://www.terraform.io/docs/providers/aws/d/availability_zones.html) - https://github.com/terraform-providers/terraform-provider-aws/issues/11136, https://github.com/terraform-providers/terraform-provider-aws/pull/12400
* [x] [`aws_ec2_transit_gateway_dx_gateway_attachment`](https://www.terraform.io/docs/providers/aws/d/ec2_transit_gateway_dx_gateway_attachment.html)
* [x] [`aws_ec2_transit_gateway_vpn_attachment`](https://www.terraform.io/docs/providers/aws/d/ec2_transit_gateway_vpn_attachment.html) - https://github.com/terraform-providers/terraform-provider-aws/pull/12415
* [x] [`aws_launch_template`](https://www.terraform.io/docs/providers/aws/d/launch_template.html) - https://github.com/terraform-providers/terraform-provider-aws/issues/8367, https://github.com/terraform-providers/terraform-provider-aws/pull/12403
* [x] [`aws_prefix_list`](https://www.terraform.io/docs/providers/aws/d/prefix_list.html) - https://github.com/terraform-providers/terraform-provider-aws/pull/12416
* [x] [`aws_vpc_endpoint_service`](https://www.terraform.io/docs/providers/aws/d/vpc_endpoint_service.html) - https://github.com/terraform-providers/terraform-provider-aws/issues/11168, https://github.com/terraform-providers/terraform-provider-aws/pull/12404

### Potential Terraform Configuration

```hcl
data "aws_availability_zones" "available" {
  filter {
    name   = "opt-in-status"
    values = ["opted-in"]
  }
}
```

**Comment by bflad** [comment]
All of these have been implemented and will release in version 2.55.0 of the Terraform AWS Provider. Thanks to @DrFaust92 for the implementation. 👍
