### ISSUE TITLE
Upgrade to Terraform Plugin SDK v2

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#12087]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

_NOTE: The work on Terraform Plugin SDK version 2 is ongoing. This issue is a placeholder for any dependencies._

### Required Changes compatible with V1 of the SDK
- [x] Remove `Partial()`/`SetPartial` usage #12083
- [x] DisableBinaryDriver for unsupported tests, mainly checks using TypeSet hashes
- [x] Develop and use alternative techniques for validating the state of `TypeSet` elements #13556 
- [x] Enable TF_SCHEMA_PANIC_ON_ERROR (default is on in V2) and identify panics/bugs. V2 of the SDK removes this env var and panics if TF_ACC is enabled #13312
- [x] Move file fixtures to child directory of `./aws` ie `./aws/files/mysql-5-6-xtrabackup.tar.gz` #13308
- [x] Ensure use of `NonRetryableError`/`RetryableError` passes non-nil #14104 
- [x] Switch to newly named validation functions #11844
- [x] Remove PromoteSingle usage
- [x] Ensure TypeMap only has Elem of primitive homogenous type (no *schema.Resource).
- [x] Remove UnsafeSetFieldRaw usage
- [x] Use custom provider name workaround for multi account/region tests #14312 

### Required Changes when switching to V2

- [x] Search and replace now broken signatures/types, this includes `terraform.ResourceProvider` `terraform.ResourceProviderFactory` and making the first argument of `CustomizeDiffFuncs` a context. #14432 
- [x] Ensure all tests and provider are compatible with the V2 binary test "process model". (Use TypeSet helpers, and be careful with concurrent design) #14067 #14381 
- [x] Remove "removed" attributes from schema as that feature has been cut. If the move to V2 SDK is a major version bump and you are ready to remove deprecated attributes, they should now go straight to deletion. #14001 

### Optional Changes

- [x] Remove usage of Exists (this is only deprecated in V2) #9953 

Linter rules:

- [x] #11869
- [x] #11870
- [x] #11871
