### ISSUE TITLE
Add Outpost attribute Support to all relevant resources

### ISSUE THREAD

**Issue by DrFaust92** [terraform-providers/terraform-provider-aws#12302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add outpost to all relevant resources

### New or Affected Resource(s)

- [x] `data_source_aws_subnet` - #12097
- [x] `data_source_aws_instance` - #12330
- [x] `data_source_aws_ebs_volume` - #12439
- [x] `data_source_aws_network_interface` - #12440
- [x] `resource_aws_subnet` - #12097
- [x] `resource_aws_ebs_volume` - #12439
- [x] `resource_aws_instance`
- [x] `resource_aws_network_interface`
- [ ] `resource_aws_emr_cluster`

### References

https://aws.amazon.com/about-aws/whats-new/2019/12/announcing-general-availability-of-aws-outposts/

**Comment by ewbankkit** [comment]
We'll also need to support the associated networking components, [local gateways](https://docs.aws.amazon.com/outposts/latest/userguide/outposts-local-gateways.html) and [customer-owned address pools](https://docs.aws.amazon.com/outposts/latest/userguide/outposts-networking-components.html#ip-addressing).

Potential data sources:
* `aws_local_gateway`
* `aws_local_gateway_route_table`
* `aws_local_gateway_route_table_virtual_interface_group_association`
* `aws_local_gateway_virtual_interface`
* `aws_local_gateway_virtual_interface_group`
* `aws_coip_pool`

Potential resources:
* `aws_local_gateway_route`
* `aws_local_gateway_route_table_vpc_association`

**Comment by johnbarney** [comment]
I'll have time to take on some of these tasks. Would you prefer it in my current pull request #12097 or would you prefer a new PR per resource?

**Comment by DrFaust92** [comment]
I think that a PR per resource would be best.

**Comment by johnbarney** [comment]
Both resource_aws_instance and resource_aws_network_interface do not support outpost_arn parameter in the AWS API. I believe they inherit from being assigned to a subnet with outpost_arn assigned.

**Comment by johnbarney** [comment]
> Both resource_aws_instance and resource_aws_network_interface do not support outpost_arn parameter in the AWS API. I believe they inherit from being assigned to a subnet with outpost_arn assigned.

Now that I have access to an Outpost, I've verified the above. Only Subnet and EBS Volume accept outpost_arn.

**Comment by DrFaust92** [comment]
> Both resource_aws_instance and resource_aws_network_interface do not support outpost_arn parameter in the AWS API. I believe they inherit from being assigned to a subnet with outpost_arn assigned.

seems like it, but they have a read only field that can be set to computed.

**Comment by johnbarney** [comment]
> seems like it, but they have a read only field that can be set to computed.

Good point. Added to my Instance PR to include this. Will add it to ENI as well.

**Comment by johnbarney** [comment]
Now that you guys have Outpost access (I think you guys actually have access to the same one I do), please let me know what resources I can contribute without duplicating efforts with your team. I'm working on the back end to get approval for continued support for this ticket.

**Comment by bflad** [comment]
Hi @johnbarney 👋 If you're able and willing, it might be great for you to pick up the EC2 Local Gateway Virtual Interface (Group) data source support! The implementation for those will be similar to your previous (much appreciated!) contributions. 🎉 

The EC2 API just added some additional EC2 Subnet + COIP support, which I created separate issues for: #13170 / #13171

We also may want to consider closing this issue and creating separate ones for the remaining functionality, just so we can more easily assign folks and have good definitions for "done". For now I'll leave it though.

**Comment by bflad** [comment]
Hi folks 👋 Please note that this issue is being split to ensure we have a definition of done for each unit of work since "support all X" issues tend to introduce scope creep over time.

I have created the following feature request issues:

- New Resource: `aws_ec2_local_gateway_route_table_vpc_association`: #13501
- New Data Source: `aws_ec2_local_gateway_virtual_interface_group`: #13502
- New Resource: `aws_ec2_local_gateway_route`: #13503
- New Data Source: `aws_ec2_local_gateway_virtual_interface(s)`: #13504

If you have needs for other enhancements, please create [new GitHub issues following the feature request template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Thanks!
