### ISSUE TITLE
awsproviderlint: New Check: Prefer aws_ami data source instead of hardcoded Amazon Machine Image identifiers

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#12994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To ensure test configurations are region and partition agnostic, any hardcoded AMI identifiers (ami-[a-f0-9]{8,17}) should be replaced with the `aws_ami` data source.

**This check was added** in #14031 and is [AWSAT002](https://github.com/terraform-providers/terraform-provider-aws/tree/master/awsproviderlint/passes/AWSAT002). We'll keep this issue open while fixes are made that are identified by the check.

#### Flagged Code

In test configuration:
```
ami-123456
```
#### Passing Code

In test configuration:
```
data "aws_ami" "example" {
  # ... configuration ...
}
```

### To Do

- [x] data_source_aws_instance_test.go (#14145)
- [x] data_source_aws_launch_configuration_test.go (#14147)
- [x] resource_aws_autoscaling_attachment_test.go (#14148)
- [x] resource_aws_autoscaling_group_test.go (#14222)
- [x] resource_aws_autoscaling_lifecycle_hook_test.go (#14321)
- [x] resource_aws_autoscaling_notification_test.go (#14323)
- [x] resource_aws_autoscaling_schedule_test.go (#14325)
- [x] resource_aws_eip_association_test.go (#14232)
- [x] resource_aws_elb_attachment_test.go (#14235)
- [ ] resource_aws_instance_test.go (#14159, original fix) (#15143, second fix)
- [x] resource_aws_launch_template_test.go (#14233)
- [x] resource_aws_network_interface_attachment_test.go (#14234)
- [x] resource_aws_network_interface_test.go (#14330)
- [x] resource_aws_route_test.go (#14174)
- [x] resource_aws_spot_fleet_request_test.go (#14083)
- [x] resource_aws_spot_instance_request_test.go (#14082)
- [x] validators_test.go (#15142)

**Comment by ewbankkit** [comment]
There are some configuration generator functions available for common AMIs:

https://github.com/terraform-providers/terraform-provider-aws/blob/dcb00966d9ec8383883ad62750cb2455fedd96f9/aws/resource_aws_instance_test.go#L4379-L4440

**Comment by YakDriver** [comment]
Relates #14031 that added the check

**Comment by bflad** [comment]
@YakDriver this looks really close to complete, do you think we could get this turned on this week?

```console
$ awsproviderlint -AWSAT002 ./aws
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_instance_test.go:3836:46: AWSAT002: AMI IDs should not be hardcoded
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_instance_test.go:4308:53: AWSAT002: AMI IDs should not be hardcoded
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/validators_test.go:1182:14: AWSAT002: AMI IDs should not be hardcoded
```

**Comment by YakDriver** [comment]
@bflad `validators_test` is ready for review #15142. 2 of the 3 `instance` tests are easy but the other is an AMI in `us-west-2` with `RootDeviceName`: `/dev/sda1`; but actual root: `/dev/sda` (`ami-ef5b69df`). I'll need more investigation into how/why such an AMI exists.

**Comment by bflad** [comment]
@YakDriver I feel like there may have been one very special instance test that was setup to cover a very specific regression due to the block setup of a specific AMI, which might be that one -- if I'm remembering that correctly (or `git blame` can verify), then that one test can be setup to run just in `us-west-2` and ignored in the linter since trying to find other similar AMIs is likely more work than benefit. 👍

**Comment by YakDriver** [comment]
@bflad The exciting #15143 PR fixes:

1. ignore the specific regression (`TestAccAWSInstance_rootBlockDeviceMismatch`),
2. reworked the other test for either partition (`TestAccAWSInstance_multipleRegions`), and
3. enabled `AWSAT002`
