### ISSUE TITLE
 Technical Debt Theme: Resolve Acceptance Test Failures (RDS)

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#14384]
### Description

This is a meta-issue which tracks the list of RDS Acceptance Tests which now consistently fail. The August-October 2020 [Roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/master/ROADMAP.md) for the AWS Provider includes a technical debt theme which decides an area of debt upon which we want to apply focus. 

The focus for this period is improving our Acceptance Test suite. This covers resolving failing and flaky tests. Our initial focus will be to resolve failing tests which exist within our [Core Service](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CORE_SERVICES.md) list.

## RDS Tests Currently Failing

- [x] `TestAccAWSRDSClusterEndpoint_tags` (moved to #14570)
- [x] `TestAccAWSDbInstanceDataSource_basic` #14526
- [x] `TestAccAWSDbClusterSnapshotDataSource_MostRecent` #14527
- [ ] `TestAccAWSDBInstance_S3Import` (will be covered by #13391)
- [ ] `TestAccAWSRDSCluster_SnapshotIdentifier_PreferredBackupWindow`
- [ ] `TestAccAWSRDSCluster_s3Restore` (will be covered by #13391)

**Comment by bflad** [comment]
The S3 import test failures may involve an AWS Support case to resolve if it is not a simple version adjustment since they require a custom backup file and the error message is nondescript. Further tracking for that can be done with: https://github.com/terraform-providers/terraform-provider-aws/issues/13391

The `TestAccAWSRDSCluster_SnapshotIdentifier_PreferredBackupWindow` failure can be tracked with this specific issue: https://github.com/terraform-providers/terraform-provider-aws/issues/14981
