### ISSUE TITLE
Avoid Hardcoding Instance Classes with Dynamic Approach

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#14882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The availability of database instance classes with specific parameters has two problems:

1. Over time the options change
2. The options are different across partitions

This is a DocDB example of an error you get when you attempt to request a set of parameters that is not valid:

```
Error: error creating DocDB Instance: InvalidParameterCombination: RDS does not support
creating a DB instance with the following combination: DBInstanceClass=db.r4.large,
Engine=docdb, EngineVersion=3.6.0, LicenseModel=na. For supported combinations of
instance class and database engine version, see the documentation.
```

This same error can come up with the four resources below.

Data sources such as associated with #14834 would be helpful. However, for those who don't want to update configurations and for provider acceptance testing, it will be helpful to be able to pick a valid combination (e.g., the smallest, biggest, middle-of-the-road), without having to know all the parameter details or hardcode them into a configuration.

### New or Affected Resource(s)

- [x] aws_docdb_cluster_instance (#14926)
- [x] aws_rds_cluster_instance (#14834)
- [x] aws_neptune_cluster_instance (#14928)

### Potential Terraform Configuration

```hcl
data "aws_rds_orderable_db_instance" "test" {
  availability_zone_group = "us-west-2-lax-1"
  engine = "mysql"
  engine_version = "5.7"
  license_model = "general-public-license"

  preferred_instance_type = "smallest"
}
```

### References

* #14834
