### ISSUE TITLE
tests/provider: API Gateway Endpoint Configuration type EDGE is not supported in GovCloud (US)

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#15071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As noted in the documentation (e.g., [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api)), the API gateway service supports `EDGE`, `REGIONAL` or `PRIVATE` types in the standard/commercial partition (`aws`). However, the `EDGE` type, which is the default type, is not supported is GovCloud (US).

Currently, provider acceptance tests that either don't specify a type or specify `EDGE` as the type are failing in GovCloud. These tests should be skipped on GovCloud.

### Affected Resource(s)

Merging these fixes will result in 82 less GovCloud test failures.

- [x] aws_api_gateway_authorizer (#15072)
- [x] aws_api_gateway_deployment (#15074)
- [x] aws_api_gateway_documentation_part (#15075)
- [x] aws_api_gateway_documentation_version (#15076)
- [x] aws_api_gateway_gateway_response (#15077)
- [x] aws_api_gateway_integration (#15077)
- [x] aws_api_gateway_integration_rresponse (#15077)
- [x] aws_api_gateway_method (#15078)
- [x] aws_api_gateway_method_response (#15078)
- [x] aws_api_gateway_method_settings (#15078)
- [x] aws_api_gateway_model (#15079)
- [x] aws_api_gateway_request_validator (#15079)
- [x] aws_api_gateway_resource (#15079)
- [x] aws_api_gateway_rest_api (#15069)
- [x] aws_api_gateway_stage (#15079)
- [x] aws_api_gateway_usage_plan (#15080)
- [x] aws_api_gateway_usage_plan_key (#15080)

### References

* hashicorp/terraform-plugin-sdk#568

**Comment by YakDriver** [comment]
All issues fixed! 👍
